###############################################################################
#
# Makefile for a python script, project 10
# 
# Students:
# Eyal Porges, ID 304789480, eyal.porges@mail.huji.ac.il
# Yoav Levy, ID 314963257, yoav.levy@mail.huji.ac.il
#
###############################################################################
all:
	chmod a+x JackCompiler
