###############################################################################
#
# Makefile for a python script, project 6
#
# Students:
# Eyal Porges, ID 304789480, eyal.porges@mail.huji.ac.il
# Yoav Levy, ID 314963257, yoav.levy2@mail.huji.ac.il
#
###############################################################################
all:
	chmod a+x Assembler
